### ISSUE TITLE
Question about this lib...

### ISSUE THREAD

**Issue by bmbariah** [sonountaleban/defold-crypto#1]
Hi, am trying to encrypt a string in my Defold game to sha512 hash before sending it via network but the value I get using this lib and a SHA512 generator such as [https://passwordsgenerator.net/sha512-hash-generator/](Hash Password Generator) is different..

I'm I missing something?

Code `pprint(crypto.hmac(crypto.sha512, "This is a test!!!", "generateSHA512"))`

**Comment by bmbariah** [comment]
Nevermind...I found the correct function 

Thanks for the lib.

**Comment by sonountaleban** [comment]
Hey, what is the correct function?

G.

**Comment by bmbariah** [comment]
`crypto.digest(crypto.sha512, "This is a test!!!")`

**Comment by sonountaleban** [comment]
Cool. :)
